name: aesthetics_labs_admin
description: "Aesthetics Labs Admin App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  # firebase dependencies start
  cloud_firestore: ^5.6.11
  firebase_core: ^3.15.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  image_picker: ^1.0.7
  image_picker_for_web: ^3.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  booking_calendar:
    path: ./booking_calendar
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  csv: ^6.0.0
  excel: ^4.0.3
  table_calendar: ^3.0.9
  syncfusion_flutter_calendar: ^29.2.5
  fl_chart: ^0.66.2
  # firebase dependencies end

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  

  assets:
    - assets/